name: Create PR for Official Images Repo

on:
  push:
    branches:
      - 'main'
    paths:
      - 'old-solr-versions'
      - 'generate-stackbrew-library.sh'
      - '[0-9]+.[0-9]+/**'

jobs:
  test:
    # Only run this job for the apache repo, not on any forks
    if: github.repository_owner == 'apache'

    name: Create PR

    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: Checkout official-images fork
        uses: actions/checkout@v3
        with:
          repository: docker-library/official-images
          path: official-images
      - name: check headcommit message
        id: commit
        run: |
          message="$(jq '.head_commit.message' $GITHUB_EVENT_PATH | sed -E 's/^#/ #/g' | sed -E 's/(#[0-9]+)$/\1 /g' | sed -E 's/([^a-zA-Z])(#[0-9]+[^0-9])/\1apache\/solr-docker\2/g' | tr -d \")"  # get the message, substituting the github links
          echo ::set-output name=title::${message%%\\n*}   # get the title
      - name: Install BashBrew
        run: |
          mkdir -p "${HOME}/.local/bin"
          wget -nv --output-document="${HOME}/.local/bin/bashbrew" https://github.com/docker-library/bashbrew/releases/download/v0.1.3/bashbrew-amd64
          chmod a+x "${HOME}/.local/bin/bashbrew"
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Generate new Solr manifest
        run: ./generate-stackbrew-library.sh > official-images/library/solr
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: official-images
          push-to-fork: docker-solr/official-images
          add-paths: library/solr
          branch: apache-solr-automated-pr
          commit-message: |
            Apache Solr - ${{ steps.commit.outputs.title}}
          title: "Apache Solr - ${{ steps.commit.outputs.title}}"
          body: |
            Apache Solr:
            
            ${{ steps.commit.outputs.title }}
            
            See apache/solr-docker@${{ github.sha }} for the triggering commit.
            
            Relevant Maintainers: @HoustonPutman @janhoy @dsmiley @madrob
            
            This is an automated PR based on a change made in the https://github.com/apache/solr-docker repository's `main` branch.
          delete-branch: true
          token: ${{ secrets.DOCKER_SOLR_BUILD_PAT }}
